//! Build script for CUDA kernel compilation.
//!
//! Compiles `src/cuda/kernel.cu` to PTX using nvcc when the CUDA toolkit is
//! available.  The resulting PTX is embedded in the binary via
//! `include_str!` so the CUDA runtime can load it at startup.
//!
//! If nvcc is not found, a stub PTX is generated and the CUDA backend will
//! fail at runtime with a helpful error message.
//!
//! nvcc implicitly `#include <cuda_runtime.h>` into every translation unit,
//! which drags in the host C++ standard library.  Recent MSVC STL versions
//! (VS 2026 / MSVC 14.51) hard-require CUDA >= 13.2 (STL1002) and cannot be
//! parsed by the CUDA 11.x frontend.  Since `kernel.cu` is compute-only and
//! never touches the host runtime, we generate a minimal stub `cuda_runtime.h`
//! into OUT_DIR and put it FIRST on nvcc's include path so the implicit
//! include resolves to the stub instead of the toolkit header.  Combined with
//! `-allow-unsupported-compiler` this makes the CUDA build robust to any
//! MSVC/CUDA version combination.

use std::env;
use std::path::PathBuf;
use std::process::Command;

/// Minimal `${OUT_DIR}/cuda_runtime.h` replacement - see module docs.
const STUB_CUDA_RUNTIME_H: &str = r#"// Stub cuda_runtime.h - compute-only replacement generated by build.rs.
// Intercepts nvcc's implicit <cuda_runtime.h> include so the host C++ standard
// library is never pulled in (new MSVC STL rejects CUDA < 13.2 and cannot be
// parsed by CUDA 11.x).  The kernel only needs nvcc built-ins: threadIdx,
// blockIdx and blockDim (from device_launch_parameters.h), __syncthreads()
// (compiler builtin).  The kernel uses inline PTX (atom.add.u32) instead of
// the atomicAdd builtin, which is never name-resolved under the minimal
// headers and would emit an extern call the driver JIT cannot resolve.
#ifndef LUCKFIND_STUB_CUDA_RUNTIME_H
#define LUCKFIND_STUB_CUDA_RUNTIME_H
#include <device_launch_parameters.h>
#if !defined(__CUDACC__) || defined(__CUDACC_RTC__)
#error "stub cuda_runtime.h is only valid for nvcc device code (__CUDACC__)"
#endif
#endif
"#;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let kernel_src = manifest_dir.join("src/cuda/kernel.cu");
    let ptx_out = out_dir.join("luckfind.ptx");

    // Try to find nvcc
    let nvcc_path = find_nvcc();

    match nvcc_path {
        Some(nvcc) => {
            println!("cargo:rerun-if-changed={}", kernel_src.display());
            println!("cargo:rerun-if-changed={}", manifest_dir.join("src/cuda/minimal_cuda.h").display());
            println!("cargo:rerun-if-env-changed=CUDA_PATH");
            println!("cargo:rerun-if-env-changed=CUDA_HOME");
            println!("cargo:rerun-if-env-changed=CUDA_ARCH");
            // PATH too: on Windows nvcc needs cl.exe (MSVC) in PATH, and cargo
            // only reruns the build script when a *declared* env var changes.
            // Without this, fixing the environment (adding cl.exe / running
            // under vcvars64.bat) would NOT retrigger the nvcc compile, leaving
            // a stale stub PTX embedded in the binary.
            println!("cargo:rerun-if-env-changed=PATH");

            // Stub cuda_runtime.h shadows the toolkit header (see module docs).
            std::fs::write(out_dir.join("cuda_runtime.h"), STUB_CUDA_RUNTIME_H)
                .expect("Failed to write stub cuda_runtime.h");

            // Compile .cu -> .ptx
            // -ptx: generate PTX only (no cubin/exe)
            // -O3: optimize
            // -allow-unsupported-compiler: skip nvcc's MSVC version check (the
            //   stub runtime means an old CUDA + new MSVC combo still works).
            // -I{out_dir}: resolve the implicit <cuda_runtime.h> to our stub.
            // -Xcompiler /wd4819: silence codepage-936 C4819 warnings for
            //   UTF-8 sources with CJK comments on Chinese-schema systems.
            // -arch: sm_75 (Turing+, GTX 16xx / RTX 20xx and newer) by default;
            //   override via the CUDA_ARCH env var (e.g. sm_52 for Maxwell).
            let arch = env::var("CUDA_ARCH").unwrap_or_else(|_| "sm_75".to_string());

            let output = Command::new(&nvcc)
                .args(&[
                    "-allow-unsupported-compiler",
                    "-Xcompiler",
                    "/wd4819",
                    "-I",
                    out_dir.to_str().unwrap(),
                    "-ptx",
                    "-O3",
                    &format!("-arch={}", arch),
                    "-o",
                    ptx_out.to_str().unwrap(),
                    kernel_src.to_str().unwrap(),
                ])
                .output()
                .expect("Failed to execute nvcc");

            if !output.status.success() {
                // Compilation failed — this often happens when cl.exe (MSVC) is
                // not in PATH (nvcc needs it on Windows).  Fall back to a stub
                // PTX so the build still succeeds.
                eprintln!("cargo:warning=nvcc compilation failed ({}):", nvcc.display());
                eprintln!("cargo:warning={}", String::from_utf8_lossy(&output.stderr));
                eprintln!("cargo:warning=CUDA backend will be unavailable at runtime.");
                eprintln!("cargo:warning=Run from a Visual Studio Developer Command Prompt for CUDA support.");

                write_stub_ptx(&ptx_out);
            } else {
                println!("cargo:rustc-cfg=cuda_compiled");
            }
        }
        None => {
            // No nvcc found — generate a stub PTX that will fail at runtime
            // with a clear error message.
            eprintln!("cargo:warning=nvcc not found — CUDA backend will be unavailable.");
            eprintln!("cargo:warning=Install CUDA toolkit from https://developer.nvidia.com/cuda-downloads");
            eprintln!("cargo:warning=to enable the CUDA GPU backend.");

            write_stub_ptx(&ptx_out);
        }
    }

    // Tell cargo where to find the PTX
    println!("cargo:rustc-env=PTX_PATH={}", ptx_out.display());
}

/// Write a minimal stub PTX when CUDA compilation is not available.
fn write_stub_ptx(path: &std::path::Path) {
    let stub_ptx = b"//
// STUB PTX -- CUDA toolkit not available at build time.
// Install CUDA toolkit and rebuild to enable the CUDA backend.
//
.version 7.0
.target sm_75
.address_size 64

.entry luckfind_kernel()
{ ret; }
";
    std::fs::write(path, stub_ptx).expect("Failed to write stub PTX");
}

/// Find nvcc in PATH or common CUDA installation locations.
fn find_nvcc() -> Option<PathBuf> {
    // Check PATH first
    if let Ok(path) = env::var("PATH") {
        for dir in path.split(';').filter(|s| !s.is_empty()) {
            let candidate = PathBuf::from(dir).join("nvcc.exe");
            if candidate.exists() {
                return Some(candidate);
            }
        }
    }

    // Check CUDA_PATH / CUDA_HOME
    for env_var in &["CUDA_PATH", "CUDA_HOME"] {
        if let Ok(cuda_path) = env::var(env_var) {
            let candidate = PathBuf::from(&cuda_path).join("bin/nvcc.exe");
            if candidate.exists() {
                return Some(candidate);
            }
            // Also try without .exe (in case of WSL or similar)
            let candidate = PathBuf::from(&cuda_path).join("bin/nvcc");
            if candidate.exists() {
                return Some(candidate);
            }
        }
    }

    // Check common installation paths
    let common_paths = [
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.3\bin\nvcc.exe",
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin\nvcc.exe",
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc.exe",
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin\nvcc.exe",
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe",
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\nvcc.exe",
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc.exe",
        r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc.exe",
    ];

    for path in &common_paths {
        let candidate = PathBuf::from(path);
        if candidate.exists() {
            return Some(candidate);
        }
    }

    None
}
